name: Manually destroy cluster

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        default: 'warning'

jobs:
  terraform_destroy:
    name: 'Terraform destroy'
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:
    - name: Download tf.plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
    - name: Terraform destroy
      run: terraform destroy -auto-approve tf.plan